version: '3'
services:
  nginx:
    restart: always
    build: ./dockerfiles/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/www/blog:/var/www/blog"
      - "/var/www/ssl/certs:/var/www/ssl/certs"
      - "$PWD/dockerfiles/nginx/conf.d:/etc/nginx/conf.d"
    command: /bin/bash /build.sh
    env_file:
      - docker.env
    extra_hosts:
      - "raw.githubusercontent.com:199.232.96.133"
    container_name: "nginx"
  nodejs:
    restart: always
    build: ./dockerfiles/nodejs
    ports:
      - "4000:4000"
    volumes:
      - "/var/www/blog:/var/www/blog"
    env_file:
      - docker.env
    container_name: "nodejs"
  php:
    restart: always
    build: ./dockerfiles/php
    expose:
      - "9000"
    volumes:
      - "/var/www/blog:/var/www/blog"
    env_file:
      - docker.env
    container_name: "php"