version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - "$PWD/dockerfiles/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "$PWD/dockerfiles/nginx/conf.d:/etc/nginx/conf.d"
      - "/var/www/blog:/var/www/blog"
    container_name: "nginx"
  nodejs:
    build: ./dockerfiles/nodejs
    ports:
      - "4000:4000"
    volumes:
      - "/var/www/blog:/var/www/blog"
    container_name: "nodejs"
  php:
    build: ./dockerfiles/php
    expose:
      - "9000"
    volumes:
      - "/var/www/blog:/var/www/blog"
    container_name: "php"